version: '3.9'

services:
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postg_vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
  
  # migration:
  #   build:
  #     context: ./api/
  #   restart: on-failure
  #   depends_on:
  #     - db
  #   env_file:
  #     - ./api/.env.docker
  #   entrypoint: [ /bin/sh ]
  #   command:
  #     - -c
  #     - /app/GPAT migrate up

  api:
    image: cosmtrek/air
    ports:
      - 8000:8000
    volumes:
      - ./api/:/go/src/app/:ro
    environment:
      - air_wd=/go/src/app/
    command: |
      -c /go/src/app/air.toml
    depends_on:
      - db
      # - migration

volumes:
  postg_vol:
