-- +migrate Up
CREATE TABLE IF NOT EXISTS "labals" (
  "id" VARCHAR (50) PRIMARY KEY NOT NULL,
  "name" VARCHAR (50),
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP
);
