// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package models

import (
	"database/sql"
	"time"
)

type AssignedLabal struct {
	ID           string         `json:"id"`
	LabalID      string         `json:"labal_id"`
	PrID         sql.NullString `json:"pr_id"`
	IssueID      sql.NullString `json:"issue_id"`
	ActivityType string         `json:"activity_type"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
}

type Assignee struct {
	ID             string         `json:"id"`
	CollaboratorID string         `json:"collaborator_id"`
	PrID           sql.NullString `json:"pr_id"`
	IssueID        sql.NullString `json:"issue_id"`
	ActivityType   string         `json:"activity_type"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
}

type Branch struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Url          sql.NullString `json:"url"`
	IsDefault    bool           `json:"is_default"`
	RepositoryID string         `json:"repository_id"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
}

type Collaborator struct {
	ID              string         `json:"id"`
	Login           string         `json:"login"`
	Name            sql.NullString `json:"name"`
	Email           sql.NullString `json:"email"`
	Url             sql.NullString `json:"url"`
	AvatarUrl       sql.NullString `json:"avatar_url"`
	WebsiteUrl      sql.NullString `json:"website_url"`
	GithubCreatedAt sql.NullTime   `json:"github_created_at"`
	GithubUpdatedAt sql.NullTime   `json:"github_updated_at"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
}

type Commit struct {
	ID                  string         `json:"id"`
	HashID              string         `json:"hash_id"`
	Message             sql.NullString `json:"message"`
	BranchID            string         `json:"branch_id"`
	PrID                sql.NullString `json:"pr_id"`
	AuthorID            string         `json:"author_id"`
	Url                 sql.NullString `json:"url"`
	CommitUrl           sql.NullString `json:"commit_url"`
	GithubCommittedTime sql.NullTime   `json:"github_committed_time"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
	DeletedAt           sql.NullTime   `json:"deleted_at"`
}

type Issue struct {
	ID                        string         `json:"id"`
	Title                     string         `json:"title"`
	Status                    string         `json:"status"`
	Url                       sql.NullString `json:"url"`
	Number                    sql.NullInt32  `json:"number"`
	AuthorID                  string         `json:"author_id"`
	RepositoryCollaboratorsID string         `json:"repository_collaborators_id"`
	GithubClosedAt            sql.NullTime   `json:"github_closed_at"`
	GithubCreatedAt           sql.NullTime   `json:"github_created_at"`
	GithubUpdatedAt           sql.NullTime   `json:"github_updated_at"`
	CreatedAt                 time.Time      `json:"created_at"`
	UpdatedAt                 time.Time      `json:"updated_at"`
	DeletedAt                 sql.NullTime   `json:"deleted_at"`
}

type Labal struct {
	ID        string         `json:"id"`
	Name      sql.NullString `json:"name"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
}

type Organization struct {
	ID              string         `json:"id"`
	Login           string         `json:"login"`
	Name            sql.NullString `json:"name"`
	Email           sql.NullString `json:"email"`
	Location        sql.NullString `json:"location"`
	Description     sql.NullString `json:"description"`
	Url             sql.NullString `json:"url"`
	AvatarUrl       sql.NullString `json:"avatar_url"`
	WebsiteUrl      sql.NullString `json:"website_url"`
	GithubUpdatedAt sql.NullTime   `json:"github_updated_at"`
	GithubCreatedAt sql.NullTime   `json:"github_created_at"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
}

type OrganizationCollaborator struct {
	ID             string       `json:"id"`
	OrganizationID string       `json:"organization_id"`
	CollaboratorID string       `json:"collaborator_id"`
	CreatedAt      time.Time    `json:"created_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
	DeletedAt      sql.NullTime `json:"deleted_at"`
}

type PullRequest struct {
	ID                        string         `json:"id"`
	Title                     sql.NullString `json:"title"`
	Status                    sql.NullString `json:"status"`
	Url                       sql.NullString `json:"url"`
	IsDraft                   sql.NullBool   `json:"is_draft"`
	Branch                    sql.NullString `json:"branch"`
	Number                    sql.NullInt32  `json:"number"`
	AuthorID                  string         `json:"author_id"`
	RepositoryCollaboratorsID string         `json:"repository_collaborators_id"`
	GithubClosedAt            sql.NullTime   `json:"github_closed_at"`
	GithubMergedAt            sql.NullTime   `json:"github_merged_at"`
	GithubCreatedAt           sql.NullTime   `json:"github_created_at"`
	GithubUpdatedAt           sql.NullTime   `json:"github_updated_at"`
	CreatedAt                 time.Time      `json:"created_at"`
	UpdatedAt                 time.Time      `json:"updated_at"`
	DeletedAt                 sql.NullTime   `json:"deleted_at"`
}

type Repository struct {
	ID              string         `json:"id"`
	Name            sql.NullString `json:"name"`
	IsPrivate       sql.NullBool   `json:"is_private"`
	DefaultBranch   sql.NullString `json:"default_branch"`
	Url             sql.NullString `json:"url"`
	HomepageUrl     sql.NullString `json:"homepage_url"`
	OpenIssues      sql.NullInt32  `json:"open_issues"`
	ClosedIssues    sql.NullInt32  `json:"closed_issues"`
	OpenPrs         sql.NullInt32  `json:"open_prs"`
	ClosedPrs       sql.NullInt32  `json:"closed_prs"`
	MergedPrs       sql.NullInt32  `json:"merged_prs"`
	GithubCreatedAt sql.NullTime   `json:"github_created_at"`
	GithubUpdatedAt sql.NullTime   `json:"github_updated_at"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
}

type RepositoryCollaborator struct {
	ID                         string `json:"id"`
	RepoID                     string `json:"repo_id"`
	OrganizationCollaboratorID string `json:"organization_collaborator_id"`
}

type Review struct {
	ID                string       `json:"id"`
	ReviewerID        string       `json:"reviewer_id"`
	PrID              string       `json:"pr_id"`
	Status            string       `json:"status"`
	GithubCreatedAt   sql.NullTime `json:"github_created_at"`
	GithubUpdatedAt   sql.NullTime `json:"github_updated_at"`
	GithubSubmittedAt sql.NullTime `json:"github_submitted_at"`
	CreatedAt         time.Time    `json:"created_at"`
	UpdatedAt         time.Time    `json:"updated_at"`
	DeletedAt         sql.NullTime `json:"deleted_at"`
}
