// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: pr.sql

package models

import (
	"context"
	"database/sql"
)

const getPRByID = `-- name: GetPRByID :one
SELECT pull_requests.id
FROM "pull_requests"
WHERE pull_requests.id = $1
`

func (q *Queries) GetPRByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getPRByID, id)
	err := row.Scan(&id)
	return id, err
}

const getPRCountByFilters = `-- name: GetPRCountByFilters :one
SELECT
   	COUNT(DISTINCT pr.id)
FROM
    public.pull_requests pr
JOIN
    public.repository_collaborators rc ON pr.repository_collaborators_id = rc.id
JOIN
    public.repositories r ON rc.repo_id = r.id
JOIN
    public.organization_collaborators oc ON rc.organization_collaborator_id = oc.id
JOIN
    public.organizations org ON oc.organization_id = org.id
JOIN
    public.assignees a ON pr.id = a.pr_id
LEFT JOIN
    public.collaborators coll ON a.collaborator_id = coll.id
WHERE
    pr.github_updated_at BETWEEN $1 AND $2 
    AND coll.id = ANY(string_to_array($3, ','))
    AND org.id = ANY(string_to_array($4, ','))
    AND r.id = ANY(string_to_array($5, ','))
`

type GetPRCountByFiltersParams struct {
	GithubUpdatedAt   sql.NullTime `json:"github_updated_at"`
	GithubUpdatedAt_2 sql.NullTime `json:"github_updated_at_2"`
	StringToArray     string       `json:"string_to_array"`
	StringToArray_2   string       `json:"string_to_array_2"`
	StringToArray_3   string       `json:"string_to_array_3"`
}

func (q *Queries) GetPRCountByFilters(ctx context.Context, arg GetPRCountByFiltersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPRCountByFilters,
		arg.GithubUpdatedAt,
		arg.GithubUpdatedAt_2,
		arg.StringToArray,
		arg.StringToArray_2,
		arg.StringToArray_3,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertPR = `-- name: InsertPR :one
INSERT INTO
    "pull_requests" (
        "id",
        "title",
        "status",
        "url",
        "number",
        "is_draft",
        "branch",
        "author_id",
        "repository_collaborators_id",
        "github_closed_at",
        "github_merged_at",
        "github_created_at",
        "github_updated_at"
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13
    ) RETURNING pull_requests.id
`

type InsertPRParams struct {
	ID                        string         `json:"id"`
	Title                     sql.NullString `json:"title"`
	Status                    sql.NullString `json:"status"`
	Url                       sql.NullString `json:"url"`
	Number                    sql.NullInt32  `json:"number"`
	IsDraft                   sql.NullBool   `json:"is_draft"`
	Branch                    sql.NullString `json:"branch"`
	AuthorID                  string         `json:"author_id"`
	RepositoryCollaboratorsID string         `json:"repository_collaborators_id"`
	GithubClosedAt            sql.NullTime   `json:"github_closed_at"`
	GithubMergedAt            sql.NullTime   `json:"github_merged_at"`
	GithubCreatedAt           sql.NullTime   `json:"github_created_at"`
	GithubUpdatedAt           sql.NullTime   `json:"github_updated_at"`
}

func (q *Queries) InsertPR(ctx context.Context, arg InsertPRParams) (string, error) {
	row := q.db.QueryRowContext(ctx, insertPR,
		arg.ID,
		arg.Title,
		arg.Status,
		arg.Url,
		arg.Number,
		arg.IsDraft,
		arg.Branch,
		arg.AuthorID,
		arg.RepositoryCollaboratorsID,
		arg.GithubClosedAt,
		arg.GithubMergedAt,
		arg.GithubCreatedAt,
		arg.GithubUpdatedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
