// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package models

import (
	"database/sql"
	"time"
)

type AssignedLabal struct {
	ID           string       `json:"id"`
	LabalID      string       `json:"labal_id"`
	ActivityID   string       `json:"activity_id"`
	ActivityType string       `json:"activity_type"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
}

type Assignee struct {
	ID             string         `json:"id"`
	CollaboratorID sql.NullString `json:"collaborator_id"`
	ActivityID     sql.NullString `json:"activity_id"`
	ActivityType   sql.NullString `json:"activity_type"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
}

type Branch struct {
	ID           string         `json:"id"`
	Name         sql.NullString `json:"name"`
	Url          sql.NullString `json:"url"`
	RepositoryID string         `json:"repository_id"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
}

type Collaborator struct {
	ID              string         `json:"id"`
	Name            sql.NullString `json:"name"`
	Username        string         `json:"username"`
	Email           sql.NullString `json:"email"`
	Url             sql.NullString `json:"url"`
	AvatarUrl       sql.NullString `json:"avatar_url"`
	WebsiteUrl      sql.NullString `json:"website_url"`
	GithubCreatedAt sql.NullTime   `json:"github_created_at"`
	GithubUpdatedAt sql.NullTime   `json:"github_updated_at"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
}

type Commit struct {
	ID                  string         `json:"id"`
	Message             sql.NullString `json:"message"`
	BranchID            string         `json:"branch_id"`
	AuthorID            string         `json:"author_id"`
	Url                 sql.NullString `json:"url"`
	CommitUrl           sql.NullString `json:"commit_url"`
	GithubCommittedTime sql.NullTime   `json:"github_committed_time"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
	DeletedAt           sql.NullTime   `json:"deleted_at"`
}

type Issue struct {
	ID              string         `json:"id"`
	Title           string         `json:"title"`
	Status          string         `json:"status"`
	Url             sql.NullString `json:"url"`
	AuthorID        string         `json:"author_id"`
	RepositoryID    string         `json:"repository_id"`
	GithubClosedAt  sql.NullTime   `json:"github_closed_at"`
	GithubCreatedAt sql.NullTime   `json:"github_created_at"`
	GithubUpdatedAt sql.NullTime   `json:"github_updated_at"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
}

type Labal struct {
	ID        string         `json:"id"`
	Name      sql.NullString `json:"name"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
}

type Organization struct {
	ID              string         `json:"id"`
	Login           string         `json:"login"`
	Name            sql.NullString `json:"name"`
	Email           sql.NullString `json:"email"`
	Location        sql.NullString `json:"location"`
	Description     sql.NullString `json:"description"`
	Url             sql.NullString `json:"url"`
	AvatarUrl       sql.NullString `json:"avatar_url"`
	WebsiteUrl      sql.NullString `json:"website_url"`
	GithubUpdatedAt sql.NullTime   `json:"github_updated_at"`
	GithubCreatedAt sql.NullTime   `json:"github_created_at"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
}

type OrganizationCollaborator struct {
	ID             string       `json:"id"`
	OrganizationID string       `json:"organization_id"`
	CollaboratorID string       `json:"collaborator_id"`
	CreatedAt      time.Time    `json:"created_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
	DeletedAt      sql.NullTime `json:"deleted_at"`
}

type PullRequest struct {
	ID              string         `json:"id"`
	Title           sql.NullString `json:"title"`
	Status          sql.NullString `json:"status"`
	Url             sql.NullString `json:"url"`
	IsDraft         sql.NullBool   `json:"is_draft"`
	AuthorID        string         `json:"author_id"`
	RepositoryID    string         `json:"repository_id"`
	GithubClosedAt  sql.NullTime   `json:"github_closed_at"`
	GithubMergedAt  sql.NullTime   `json:"github_merged_at"`
	GithubCreatedAt sql.NullTime   `json:"github_created_at"`
	GithubUpdatedAt sql.NullTime   `json:"github_updated_at"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
}

type Repository struct {
	ID                         string         `json:"id"`
	Name                       sql.NullString `json:"name"`
	NameWithOwner              sql.NullString `json:"name_with_owner"`
	IsPrivate                  sql.NullBool   `json:"is_private"`
	DefaultBranch              sql.NullString `json:"default_branch"`
	Url                        sql.NullString `json:"url"`
	HomepageUrl                sql.NullString `json:"homepage_url"`
	OpenIssues                 sql.NullString `json:"open_issues"`
	ClosedIssues               sql.NullString `json:"closed_issues"`
	OpenPr                     sql.NullInt32  `json:"open_pr"`
	ClosedPr                   sql.NullInt32  `json:"closed_pr"`
	MergedPr                   sql.NullInt32  `json:"merged_pr"`
	OrganizationCollaboratorID string         `json:"organization_collaborator_id"`
	GithubCreatedAt            sql.NullTime   `json:"github_created_at"`
	GithubUpdatedAt            sql.NullTime   `json:"github_updated_at"`
	CreatedAt                  time.Time      `json:"created_at"`
	UpdatedAt                  time.Time      `json:"updated_at"`
	DeletedAt                  sql.NullTime   `json:"deleted_at"`
}

type Review struct {
	ID                string         `json:"id"`
	ReviewerID        string         `json:"reviewer_id"`
	PrID              string         `json:"pr_id"`
	Status            string         `json:"status"`
	GithubCreatedAt   sql.NullString `json:"github_created_at"`
	GithubUpdatedAt   sql.NullString `json:"github_updated_at"`
	GithubSubmittedAt sql.NullString `json:"github_submitted_at"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	DeletedAt         sql.NullTime   `json:"deleted_at"`
}
