// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: query.sql

package models

import (
	"context"
)

const getOrganizationList = `-- name: GetOrganizationList :many
SELECT id, name, full_name, description, email, url, avatar_url, website_url, github_updated_at, github_created_at, created_at, updated_at, deleted_at FROM "organizations"
`

func (q *Queries) GetOrganizationList(ctx context.Context) ([]Organization, error) {
	rows, err := q.db.QueryContext(ctx, getOrganizationList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FullName,
			&i.Description,
			&i.Email,
			&i.Url,
			&i.AvatarUrl,
			&i.WebsiteUrl,
			&i.GithubUpdatedAt,
			&i.GithubCreatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
